module.exports = {
  BUSINESS_RULES: {
    MAX_ACTIVE_BORROWINGS: 5,
    STANDARD_LOAN_PERIOD_DAYS: 14,
    MAX_RENEWALS: 2,
    RENEWAL_PERIOD_DAYS: 7,
    FINE_BLOCKED_AMOUNT: 500, // ₦500
    FINE_RATE_PER_DAY: 50,    // ₦50
    MAX_ACTIVE_RESERVATIONS: 3,
    RESERVATION_EXPIRY_HOURS: 48
  }
};
